### ISSUE TITLE
How to connect

### ISSUE THREAD

**Issue by zeke800** [heregoesradio/heregoes#1]
What equipment is needed to run this? If I have an SDR and a 3m dish, would the SDR be usable as an input? Is this the entire decoding pipeline? If not, what software do you use to connect to this?

**Comment by heregoesradio** [comment]
Hi,

This is a Python library for processing GOES-R imagery data from netCDF. These netCDF files can be downloaded from [NOAA CLASS](https://www.class.noaa.gov/) or [AWS S3](https://registry.opendata.aws/noaa-goes/). They are also generated by [CSPP GEO](https://cimss.ssec.wisc.edu/csppgeo/) from the [GOES ReBroadcast (GRB)](https://www.goes-r.gov/users/docs/PUG-GRB-vol4.pdf) radio downlink. The heregoes library does not decode the GRB and it does not interface with any SDR. You can see how it is used to process imagery from netCDF in the README. Check out this community [here](https://osp.teske.net.br/) to learn more about amateur reception of GRB.

Thanks!
Here GOES Radiotelescope
